language: php

cache:
  directories:
    - bin

sudo: false

php:
  - 5.3

before_script:
  - composer self-update -n
  - composer install -n --prefer-dist -v
  - nohup php -S localhost:8080 -t features/fixtures/web > server.log 2>&1 &

script:
  - bin/phpcs --standard=PSR2 --encoding=UTF-8 --ignore="*.db,*.color,*.ttf" src/
  - bin/behat --no-snippets --verbose --profile=travis -vvv
